### ISSUE TITLE
编译报错呢，导入项目后，需要注意什么啊？

### ISSUE THREAD

**Issue by liguangze** [ReimuNotMoe/IMEIGeneratorApp#1]
External Native Build Issues
Build command failed.
Error while executing process E:\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HE:\xiangmu\IMEIGeneratorApp-master\app -BE:\xiangmu\IMEIGeneratorApp-master\app\.externalNativeBuild\cmake\release\armeabi -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-15 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\xiangmu\IMEIGeneratorApp-master\app\build\intermediates\cmake\release\obj\armeabi -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=E:\sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_TOOLCHAIN_FILE=E:\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}
-- Check for working C compiler: E:/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: E:/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: E:/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: E:/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:13 (add_library):
    src/main/cpp/libIMEI/libIMEI.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error: CMake can not determine linker language for target: native-lib
-- Generating done
-- Build files have been written to: E:/xiangmu/IMEIGeneratorApp-master/app/.externalNativeBuild/cmake/release/armeabi
Build command failed.
Error while executing process E:\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HE:\xiangmu\IMEIGeneratorApp-master\app -BE:\xiangmu\IMEIGeneratorApp-master\app\.externalNativeBuild\cmake\debug\armeabi -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-15 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\xiangmu\IMEIGeneratorApp-master\app\build\intermediates\cmake\debug\obj\armeabi -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=E:\sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-std=c++11 -DCMAKE_TOOLCHAIN_FILE=E:\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=E:\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}
-- Check for working C compiler: E:/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: E:/SDK/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done

**Comment by liguangze** [comment]
src/main/cpp/libIMEI/libIMEI.c
  src/main/cpp/libIMEI/libIMEI.h )

发现这个libIMEI文件下面没有内容，为什么还要.c跟.n呢

**Comment by liguangze** [comment]
git上查看能看到src/main/cpp/libIMEI/下有内容，下载完成后，就没有了呢，为什么不能下载呢

**Comment by ReimuNotMoe** [comment]
你可能git clone的时候没有加 -r 选项。那个空的文件夹是一个submodule。

如果你嫌麻烦的话，可以直接在Releases里下载编译好的apk。

**Comment by liguangze** [comment]
能提交一下吗，我想用用你的项目，或者方便的话加个QQ429475006
